add: usedInVMs for ClusterVirtualMachineImage, VirtualMachineImage, V…
deckhouse/virtualization-controller pull request #84
Opened 2023-08-21 07:17 UTC by universal-itengineer

Information about which VMs they are connected to has been added to the status of these resources.

2023-08-21 07:20 UTC, fl64 reviewed
fit it

2023-08-21 07:20 UTC, fl64 commented on api/clustervirtualmachineimage.yaml
> +                    A list of virtual machines that use the virtual machine disk
image

2023-08-21 07:20 UTC, fl64 commented on api/virtualmachineimage.yaml
> +                    A list of virtual machines that use the disk
image

2023-08-21 07:48 UTC, fl64 requested changes

2023-08-21 07:48 UTC, fl64 commented on api/clustervirtualmachineimage.yaml
> +                    A list of virtual machines that use image
```suggestion
                    A list of virtual machines that use the image
```

2023-08-21 07:48 UTC, fl64 commented on api/virtualmachineimage.yaml
> +                    A list of virtual machines that use image
```suggestion
                    A list of virtual machines that use the image
```

2023-08-25 09:28 UTC, distorhead approved these changes

2023-08-25 09:39 UTC, merged